Repository collinbarrett/FilterLists, pull requests merged in 2019-04, with the labels that each got.

#744 More button stuff
  src/FilterLists.Web/ClientApp/modules/home/components/detailsExpander/infoCard/UpdatedDate.tsx
  src/FilterLists.Web/ClientApp/modules/home/components/linkButtons/SubscribeButton.tsx
  src/FilterLists.Web/ClientApp/modules/home/components/linkButtons/ViewButton.tsx
  src/FilterLists.Web/ClientApp/site.css
  src/FilterLists.Web/Views/Shared/_Layout.cshtml
Labels: ui

#745 Polishing of UI changes
  src/FilterLists.Web/ClientApp/modules/home/components/detailsExpander/infoCard/UpdatedDate.tsx
  src/FilterLists.Web/ClientApp/modules/home/components/linkButtons/SubscribeButton.tsx
  src/FilterLists.Web/ClientApp/site.css
Labels: ui

#747 Date formatting, take 4
  src/FilterLists.Web/ClientApp/modules/home/components/detailsExpander/infoCard/UpdatedDate.tsx
Labels: ui

#748 Date formatting, take 5
  src/FilterLists.Web/ClientApp/modules/home/components/detailsExpander/infoCard/UpdatedDate.tsx
Labels: ui

#749 Reverting the date formatting
  src/FilterLists.Web/ClientApp/modules/home/components/detailsExpander/infoCard/UpdatedDate.tsx
Labels: ui

#750 add unsullied filter
  data/FilterList.json
  data/FilterListMaintainer.json
  data/FilterListTag.json
  data/Maintainer.json
Labels: data

#756 wrong names
  data/FilterList.json
Labels: data

#761 Mid-April pull
  data/FilterList.json
  data/FilterListLanguage.json
  data/FilterListMaintainer.json
  data/FilterListTag.json
  data/Syntax.json
  data/Tag.json
Labels: data

#766 try bumping .NET SDK ver
  .travis.yml
Labels: bug, ops

#767 sync #764 w/upstream fix
  data/FilterList.json
  data/FilterListLanguage.json
  data/FilterListMaintainer.json
  data/FilterListTag.json
  data/Maintainer.json
Labels: data

#768 sync #765 w/upstream fix
  FilterLists.sln.DotSettings
  data/FilterList.json
  data/FilterListLanguage.json
  data/FilterListMaintainer.json
  data/FilterListTag.json
  data/Software.json
  data/SoftwareSyntax.json
  data/Syntax.json
  src/FilterLists.Web/ClientApp/modules/home/components/softwareIcon/SoftwareIcon.tsx
  src/FilterLists.Web/ClientApp/modules/home/components/softwareIcon/imgs/31-AdGuard-Home.png
  src/FilterLists.Web/ClientApp/modules/home/components/softwareIcon/imgs/index.ts
Labels: data
